# ============ HUGO SETTINGS ============

baseURL = "https://blog.sklad.observer/"
title = "SKлад постов"

cleanDestinationDir = true

# TODO: https://youtu.be/1iTnkzdt1mw?t=7
# enableRobotsTXT = true

# Hugo serves static files directly at the site root
# with seemingly no option to alter this behavior.
# https://gohugo.io/content-management/static-files/
# Huh. But whatever.


# Minify some of the stuff.
# Sadly, Hugo decided to name these params `disableCSS`, `disableHTML`, etc. (with the default = `false`)
# instead of having `minifyCSS`, `minifyHTML`, etc. (with the default value of `true`).
# So you kinda have to deal with this double negation now.
# Then there's also the `minifyOutput` flag.
# When set to `false` (which is its default value),
# it disables minification completely, overriding all other params.
# Needlessly convoluted, but fortunately not that hard to figure out thanks to the docs:
# https://gohugo.io/getting-started/configuration/#configure-minify
[minify]
minifyOutput = true
disableCSS = true
# disableHTML = true
disableJS = true
# disableJSON = true
# disableSVG = true
disableXML = true

[markup.highlight]
style = "native"


# You cannot set this per-post. Annoying.
[markup.tableOfContents]
# ordered = false
# startLevel = 2
endLevel = 4

# ============ THEME SETTINGS ============

[params]
# Gets included in the footer.
author = "サンダル 傘"
# This seems to mainly affect some meta tags used by Twitter previews and whatnot.
description = "Hello, there" # TODO: change to something reasonable

# Generate Table of Contents for 600+ words long posts
toc = true
tocWordCount = 600

# Show a "Read more..." button under the post preview.
# Sadly, doesn't work for posts with `summary = "..."` set in the front matter.
readMore = true

# === Social icons ===
rssAsSocialIcon = true

[[params.social]]
id = "github"
url = "https://github.com/SandaruKasa"
