# TODO: fill in actual data

base_url = "https://example.com"
title = "It is what it is"

theme = "apollo"

compile_sass = false
build_search_index = true

[[taxonomies]]
name = "tags"

[markdown]
highlight_code = true
extra_syntaxes_and_themes = [
    "themes/atelier_syntax_highlighting/docs/archive/atelier-schemes/output/textmate/",
]
highlight_theme = "base16-atelierdune.dark"

smart_punctuation = true

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
paths_keep_dates = false

[search]
include_title = true
include_description = true
include_path = true
include_content = true


[extra] # https://www.getzola.org/themes/apollo/
toc = true

theme = "dark"
stylesheets = ["scratch.css"]

[[extra.meta]]
property = "og:title"
content = "the og title"
[[extra.meta]]
property = "og:description"
content = "the og description"

[[extra.socials]]
name = "Link1"
url = "https://example.com"
icon = "github"


[[extra.menu]]
name = "Posts"
url = "/posts"

[[extra.menu]]
name = "About"
url = "/about"


# TODO: add footer
# TODO: copy link by clicking on header
# TODO: tags
# TODO: search?
