# Zola loves caluclating absolute links (even for #anchors within a page),
# but since "/some/url" resolves from the root of the domain,
# this would ruin Zola-generated sites that don't start at the root of a domain.
# I.e. having a url pointing to "/post-1" at "https://example.com/blog/"
# resolves to "https://example.com/post-1" and not "https://example.com/blog/post-1".
# That's why Zola prepends this `base_url` to all absolute links.
# But since I have an entire subdomain, I can just set this to "/",
# which has an additional benifit of not requiring me to change this param
# every time I want to launch it without https or on localhost.
base_url = "/"
title = "SKлад постов"
minify_html = false

theme = "apollo"

compile_sass = false
build_search_index = false
generate_feed = true

[[taxonomies]]
name = "tags"

[markdown]
highlight_code = true
extra_syntaxes_and_themes = [
    "themes/atelier_syntax_highlighting/docs/archive/atelier-schemes/output/textmate/",
]
highlight_theme = "base16-atelierdune.dark"

smart_punctuation = true

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
paths_keep_dates = false

[search]
include_title = true
include_description = true
include_path = true
include_content = true


[extra] # https://www.getzola.org/themes/apollo/
# Table of contents
toc = true

favicon = "/crises.png"
theme = "dark"
stylesheets = ["scratch.css"]

[[extra.socials]]
name = "GitHUb"
url = "https://github.com/SandaruKasa"
icon = "github"


[[extra.menu]]
name = "Posts"
url = "/posts"

[[extra.menu]]
name = "About"
url = "/about"
