base_url = "https://blog.sklad.observer"
title = "SKлад постов"
minify_html = true

theme = "apollo"

compile_sass = false
build_search_index = true

[[taxonomies]]
name = "tags"

[markdown]
highlight_code = true
extra_syntaxes_and_themes = [
    "themes/atelier_syntax_highlighting/docs/archive/atelier-schemes/output/textmate/",
]
highlight_theme = "base16-atelierdune.dark"

smart_punctuation = true

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
paths_keep_dates = false

[search]
include_title = true
include_description = true
include_path = true
include_content = true


[extra] # https://www.getzola.org/themes/apollo/
toc = true

favicon = "/crises.png"
theme = "dark"
stylesheets = ["scratch.css"]

[[extra.socials]]
name = "GitHUb"
url = "https://github.com/SandaruKasa"
icon = "github"


[[extra.menu]]
name = "Posts"
url = "/posts"

[[extra.menu]]
name = "About"
url = "/about"


# TODO: add footer
# TODO: copy link by clicking on header
# TODO: tags
# TODO: search?
